FROM ubuntu:22.04
RUN \ 
    apt-get update &&\
    apt-get install -y libgomp1
RUN mkdir /komodo
WORKDIR /komodo
COPY src/komodod src/komodo-cli ./

RUN ln -sf /komodo/komodod /usr/bin/komodod && \
    ln -sf /komodo/komodo-cli /usr/bin/komodo-cli

CMD ./komodod
