FROM ubuntu:20.04
RUN \ 
    apt-get update && \
    apt-get install software-properties-common -y && \
    add-apt-repository ppa:ubuntu-toolchain-r/test -y && \
    apt-get update && \
    sudo apt-get upgrade && \
    sudo apt-get dist-upgrade && \
    apt-get install -y libgomp1 libstdc++6 binutils
RUN mkdir /komodo
WORKDIR /komodo
COPY src/komodod src/komodo-cli ./

RUN ln -sf /komodo/komodod /usr/bin/komodod && \
    ln -sf /komodo/komodo-cli /usr/bin/komodo-cli

CMD ./komodod
