name: Komodo MacOS CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  schedule:
    - cron: '0 0 * * 1'

jobs:

  macos-build:
    name: MacOS Build
    runs-on: macos-latest-large
    
    steps:
      - uses: actions/checkout@v4

      # Workaround for https://github.com/actions/setup-python/issues/577
      - name: Clean up binaries and links (macOS)
        run: |
          rm -f /usr/local/bin/2to3-3.*
          rm -f /usr/local/bin/idle3.*
          rm -f /usr/local/bin/pydoc3.*
          rm -f /usr/local/bin/python3.*
          rm -f /usr/local/bin/2to3
          rm -f /usr/local/bin/idle3
          rm -f /usr/local/bin/pydoc3
          rm -f /usr/local/bin/python3
          rm -f /usr/local/bin/python3-config

      - name: Install deps (macOS)
        run: |
          brew update
          brew tap discoteq/discoteq; brew install flock
          brew install autoconf autogen automake
          brew install binutils
          brew install protobuf
          brew install coreutils
          brew install wget
          brew install python3

      # https://www.jessesquires.com/blog/2020/01/06/selecting-an-xcode-version-on-github-ci/
      # https://github.com/actions/runner-images/issues/2619 (bsdtar issues)
      # flag for some CC tests transactions - so DO NOT USE THIS CI ARTIFACTS IN PRODUCTION!!!
      - name: Build (macOS)
        run: |
          ./zcutil/build-mac-dtest.sh -j4
          gtar -czvf komodo-macos.tar.gz src/komodod src/komodo-cli src/wallet-utility src/komodo-tx
        # env:
        #   DEVELOPER_DIR: /Applications/Xcode_13.2.1.app/Contents/Developer

      - name: Upload komodo-macos.tar.gz as artifact
        uses: actions/upload-artifact@v4
        with:
          name: komodo-macos
          path: |
            ./komodo-macos.tar.gz

  macos-test-dice-token-reards-faucet-cc:
    if: ${{ false }}

    name: Test (MacOS/Dice, Token, Faucet, Rewards)
    runs-on: macos-latest
    needs: macos-build

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (Dice, Token, Faucet, Rewards CC)
        run: |
          brew install python3 curl
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema

      - name: Download komodo-macos.tar.gz
        uses: actions/download-artifact@v4
        with:
          name: komodo-macos

      - name: Test CC (MacOS)
        run: |
          mv komodo-macos/komodo-macos.tar.gz .
          mkdir -p src
          tar xzvf komodo-macos.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh "cc_modules/test_dice.py cc_modules/test_faucet.py cc_modules/test_token.py cc_modules/test_rewards.py"

  macos-test-oracles:
    if: ${{ false }}

    name: Test (macos/OraclesCC)
    runs-on: macos-latest
    needs: macos-build

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (OraclesCC)
        run: |
          brew install python3 curl
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-macos.tar.gz
        uses: actions/download-artifact@v4
        with:
          name: komodo-macos

      - name: Oracles Test (macos)
        run: |
          mv komodo-macos/komodo-macos.tar.gz .
          mkdir -p src
          tar xzvf komodo-macos.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_oracles.py

  macos-test-baserpc:
    if: ${{ false }}

    name: Test (macos/BasicRPC)
    runs-on: macos-latest
    needs: macos-build

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (BasicRPC)
        run: |
          brew install python3 curl
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-macos.tar.gz
        uses: actions/download-artifact@v4
        with:
          name: komodo-macos

      - name: BasicRPC Test (macos)
        run: |
          mv komodo-macos/komodo-macos.tar.gz .
          mkdir -p src
          tar xzvf komodo-macos.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh basic

  macos-test-channels:
    if: ${{ false }}

    name: Test (macos/ChannelsCC)
    runs-on: macos-latest
    needs: macos-build

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (ChannelsCC)
        run: |
          brew install python3 curl
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-macos.tar.gz
        uses: actions/download-artifact@v4
        with:
          name: komodo-macos

      - name: Channels Test (macos)
        run: |
          mv komodo-macos/komodo-macos.tar.gz .
          mkdir -p src
          tar xzvf komodo-macos.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_channels.py

  macos-test-heir:
    if: ${{ false }}

    name: Test (macos/HeirCC)
    runs-on: macos-latest
    needs: macos-build

    steps:
      - uses: actions/checkout@v4

      - name: Install deps (HeirCC)
        run: |
          brew install python3 curl
          python3 -m pip install setuptools wheel
          python3 -m pip install slick-bitcoinrpc pytest wget jsonschema
      - name: Download komodo-macos.tar.gz
        uses: actions/download-artifact@v4
        with:
          name: komodo-macos

      - name: Heir Test (macos)
        run: |
          mv komodo-macos/komodo-macos.tar.gz .
          mkdir -p src
          tar xzvf komodo-macos.tar.gz
          ./zcutil/fetch-params.sh
          cd qa/pytest_komodo
          ./ci_setup.sh cc_modules/test_heir.py
